# Generated by Django 2.2 on 2019-05-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_link', models.CharField(max_length=250)),
                ('headline', models.CharField(max_length=250)),
                ('is_sarcastic', models.BooleanField()),
            ],
        ),
    ]
