# Generated by Django 2.2 on 2019-05-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarcasm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='headline',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='headline',
            name='is_sarcastic',
            field=models.IntegerField(),
        ),
    ]
