# Generated by Django 2.2 on 2019-05-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarcasm', '0002_auto_20190515_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='headline',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='headline',
            name='is_sarcastic',
            field=models.BooleanField(),
        ),
    ]
