# Generated by Django 2.2 on 2019-05-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarcasm', '0004_auto_20190515_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='article_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='headline',
            name='headline',
            field=models.CharField(max_length=250),
        ),
    ]
