# Generated by Django 2.2 on 2019-05-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarcasm', '0005_auto_20190515_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='headline',
            field=models.TextField(),
        ),
    ]
